{% set name = "semver" %}
{% set version = "3.0.1" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9ec78c5447883c67b97f98c3b6212796708191d22e4ad30f4570f840171cbce1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pysemver = semver.cli:main

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - python >=3.7

test:
  imports:
    - semver
  commands:
    - pysemver -h

about:
  home: https://github.com/k-bx/python-semver
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package to work with Semantic Versioning
  description: |
    A Python module for semantic versioning. Simplifies comparing versions.
  dev_url: https://github.com/k-bx/python-semver
  doc_url: https://github.com/k-bx/python-semver

extra:
  recipe-maintainers:
    - rmax
    - carlodri
