{% set name = "semver" %}
{% set version = "2.9.1" %}
{% set sha256sum = "723be40c74b6468861e0e3dbb80a41fc3b171a2a45bf956c245304773dc06055" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256sum }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
    - setuptools

  run:
    - python

test:
  imports:
    - semver

about:
  home: https://github.com/k-bx/python-semver
  license: BSD
  license_file: LICENSE.txt
  summary: Python package to work with Semantic Versioning
  description: |
    A Python module for semantic versioning. Simplifies comparing versions.
  dev_url: https://github.com/k-bx/python-semver
  doc_url: https://github.com/k-bx/python-semver

extra:
  recipe-maintainers:
    - rmax
    - carlodri
