{% set name = "semver" %}
{% set version = "3.0.3" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8769a03a93507fecdf19b6eefb08d5e95b462504871a61e29e09798822888c94

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pysemver = semver.cli:main

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - python >={{ python_min }}

test:
  requires:
    - python {{ python_min }}
  imports:
    - semver
  commands:
    - pysemver -h

about:
  home: https://github.com/k-bx/python-semver
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package to work with Semantic Versioning
  description: |
    A Python module for semantic versioning. Simplifies comparing versions.
  dev_url: https://github.com/k-bx/python-semver
  doc_url: https://github.com/k-bx/python-semver

extra:
  recipe-maintainers:
    - rmax
    - carlodri
