{% set name = "semver" %}
{% set version = "2.13.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: fa0fe2722ee1c3f57eac478820c3a5ae2f624af8264cbdf9000c980ff7f75e3f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  entry_points:
    - pysemver = semver:main

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - semver
  commands:
    - pysemver -h

about:
  home: https://github.com/k-bx/python-semver
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package to work with Semantic Versioning
  description: |
    A Python module for semantic versioning. Simplifies comparing versions.
  dev_url: https://github.com/k-bx/python-semver
  doc_url: https://github.com/k-bx/python-semver

extra:
  recipe-maintainers:
    - rmax
    - carlodri
