schema_version: 1

context:
  name: semver
  version: "3.1.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 14bc073439513d7773662a338f4db9829cf16c12b74b9568e2d2689975fbd7fc

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv
  python:
    entry_points:
      - pysemver = semver.cli:main

requirements:
  host:
    - pip
    - python ${{ python_min }}.*
    - setuptools
  run:
    - python >=${{ python_min }}

tests:
  - python:
      imports:
        - semver
      python_version:
        - ${{ python_min }}.*
        - "*"
  - requirements:
      run:
        - python ${{ python_min }}.*
    script:
      - pysemver -h

about:
  license: BSD-3-Clause
  license_file: LICENSE.txt
  summary: Python package to work with Semantic Versioning
  description: |
    A Python module for semantic versioning. Simplifies comparing versions.
  homepage: https://github.com/k-bx/python-semver
  repository: https://github.com/k-bx/python-semver
  documentation: https://github.com/k-bx/python-semver

extra:
  recipe-maintainers:
    - rmax
    - carlodri
