travis:
  secure:
    BINSTAR_TOKEN: hS4ZxIeRdUqN8B5kygH+7qLInznpvaRuRw/UtsTkNF1WQJN0yXBVv8N1imGSwxvfv16azcSKcK5/YjPSXoCMSR0Kj5J9CDtwdxSvJ4rza0W+LXyGW5b64/nWCD2E3k1MmvScmUzyl104QeiiJtKZaj0TNuI+111X7SwbhC1LCLx/dDJ5WDnvXo0YIJ1ClvReT2Zz9RdgPQ2tNx/v3Kaq0ap+M1a2WIJudmWc0DJ1nnebpQVtTTx9smE/0RtIBVhepF2HtnjO61wkkt4KvgEBdanv49fAMDlZfj5JNOO2byZI3AG9VgQVCWC2206QQWk+FvmjxXrkDFWE5KGVPa68KGhPf6YXdVfAUHnB20srHkcr/+MgXUrBjS1tRWkHsptZX/YT/Fn0dax6FhiIYN6lnT/ohExNCSnqyHSGx7qQgQ/0K0QINfLmsOXEoU3f/Pg8KluJwWlBfEtZHdBxXEiVVKW3AXEJYIhFbJPrHqX6euVt5VzfiFZzCdoalihr6wlql9Duk62UquxcBbM7lg4mamolkj1WEh/8GgjL3Sy/+xCfirLxdQj3zuwOF/33our+tHTeynudoAJkaJ/mHwX+PVQqqIPrE7DGHsUKvfDkJU5CIxDIEU+1ovUFTESGumHhPeovRa0euBBsxqX5dFWDEr3y9eC9aVoZssIF4yr0nEQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: false
